name: Sync LeetCode

on:
  workflow_dispatch: # Manual sync trigger capability
  schedule:
    - cron: '0 0 * * *' # Automated engine executing nightly

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Sync Pipeline
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          verbose: true
          update-readme: true
