name: Sync LeetCode

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: '0 0 * * *' # Runs automatically every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cook Solutions
        uses: jasonalvarez/leetcode-sync@v2
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
